language:
  cpp
compiler:
  - gcc
python:
  - 3.5
install:
  - sudo apt-get install libboost-all-dev
  - sudo pip install coveralls
script:
  - make test
  - python3 database/load.py -r
  - coverage run setup.py test
after_success:
  - coveralls
